### PR TITLE
node Postgres setup

### PR DESCRIPTION
**Pull request by eduardpeters**
Removing the json mock files.
Introducing PostgreSQL DB connection.
Overall project structure.

.env New variables needed:
PGHOST
PGUSER
PGDATABASE
PGPASSWORD
PGPORT

### CODE REVIEW

**Review by Rotosama — COMMENTED** [review]
Buen trabajo Eduard!!

**Review by Rotosama — APPROVED** [review]

**Review by laurapellicerrahan — COMMENTED** [review]
Good job team! :)

**Review by laurapellicerrahan — APPROVED** [review]
Perfect!

**Review by RLANFRAN86 — COMMENTED** [review]
great team!!!

**Pull request merged**
